# Generated by Django 3.2.7 on 2021-09-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptoType', models.CharField(max_length=200)),
                ('intention', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('pub_date', models.CharField(max_length=200)),
                ('belongs_to', models.IntegerField(null=True)),
            ],
        ),
    ]
